# Generated by Django 5.0.3 on 2024-03-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_content_alter_blogpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Запись блога', 'verbose_name_plural': 'Записи блога'},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='is_published',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='views',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog_previews/', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
