# Generated by Django 5.0.3 on 2024-03-13 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_version_is_active_version_is_current_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_current_version',
            field=models.BooleanField(default=False, verbose_name='Активная версия'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.CharField(max_length=100, verbose_name='Название версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(max_length=50, verbose_name='Номер версии'),
        ),
    ]
