# Generated by Django 5.0.3 on 2024-03-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Can publish posts')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
