# Generated by Django 5.0.3 on 2024-03-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Может отменять публикацию')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
